/* Generated by GOB (v2.0.15)   (do not edit directly) */

#include <glib.h>
#include <glib-object.h>


#include <gtk/gtk.h>
//#include <gnome.h>
#include <avahi-client/client.h>
#include <avahi-common/error.h>
#include <avahi-glib/glib-watch.h>
#include <avahi-client/publish.h>
#include <avahi-client/lookup.h>


#ifndef __SYNERGY_APPLET_H__
#define __SYNERGY_APPLET_H__

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


typedef enum 
{
	SYNERGY_MODE_DISABLED,
	SYNERGY_MODE_CLIENT,
	SYNERGY_MODE_SERVER
} SynergyMode;
#define SYNERGY_TYPE_MODE synergy_mode_get_type()
GType synergy_mode_get_type (void);

/**
 * A server or client host.
 */
typedef struct
{
	/**
	 * Short host name
	 */
	gchar* name;
		
	/**
	 * Ahavi host name
	 */
	gchar* avahi_name;
	
	/**
	 * IP address
	 */
	gchar* address;
	
	/**
	 * Port number
	 */
	uint16_t port;
	
	/**
	 * The host is online according to avahi
	 */
	gboolean online;
	
	/**
	 * Time of last connection
	 */
	time_t time_of_last_connection;
	
} SynergyHost;


#define SYNERGY_AVAHI_TYPE_SERVER "_synergy_server._tcp"
#define SYNERGY_AVAHI_TYPE_CLIENT "_synergy_client._tcp"


/*
 * Type checking and casting macros
 */
#define SYNERGY_TYPE_APPLET	(synergy_applet_get_type())
#define SYNERGY_APPLET(obj)	G_TYPE_CHECK_INSTANCE_CAST((obj), synergy_applet_get_type(), SynergyApplet)
#define SYNERGY_APPLET_CONST(obj)	G_TYPE_CHECK_INSTANCE_CAST((obj), synergy_applet_get_type(), SynergyApplet const)
#define SYNERGY_APPLET_CLASS(klass)	G_TYPE_CHECK_CLASS_CAST((klass), synergy_applet_get_type(), SynergyAppletClass)
#define SYNERGY_IS_APPLET(obj)	G_TYPE_CHECK_INSTANCE_TYPE((obj), synergy_applet_get_type ())

#define SYNERGY_APPLET_GET_CLASS(obj)	G_TYPE_INSTANCE_GET_CLASS((obj), synergy_applet_get_type(), SynergyAppletClass)

/*
 * Main object structure
 */
#ifndef __TYPEDEF_SYNERGY_APPLET__
#define __TYPEDEF_SYNERGY_APPLET__
typedef struct _SynergyApplet SynergyApplet;
#endif
struct _SynergyApplet {
	GObject __parent__;

	GMainLoop * main_loop;
	
	AvahiPoll* avahi_poll_api;
    AvahiGLibPoll* avahi_glib_poll;
    AvahiClient* avahi_client;
    
    AvahiServiceBrowser* avahi_service_browser;
    
    AvahiEntryGroup* avahi_entry_group;
    gchar* avahi_service_name;

	/**
	 * Mode: server, client or disabled
	 */
	SynergyMode mode;
	
	/**
	 * All known clients: online and previously used
	 */
	GList * clients;
	
	/**
	 * All known servers: online and previously used.
	 */
	GList * servers;
	
	GtkStatusIcon * status_icon_disabled;
	GtkStatusIcon * status_icon_server_enabled;
	GtkStatusIcon * status_icon_client_enabled;
	
	
	GtkMenu * menu;
	GtkDialog * settings;
	GtkDialog * client_settings;
	GtkDialog * server_settings;
};

/*
 * Class definition
 */
typedef struct _SynergyAppletClass SynergyAppletClass;
struct _SynergyAppletClass {
	GObjectClass __parent__;
};


/*
 * Public methods
 */
GType	synergy_applet_get_type	(void);

void synergy_applet_start(SynergyApplet* applet, GMainLoop * main_loop);

void synergy_applet_set_mode(SynergyApplet* applet, SynergyMode mode);

SynergyHost* synergy_applet_host_new(const gchar* name, const gchar* avahi_name, const gchar* address, const uint16_t port);
void synergy_applet_host_free(SynergyHost* host);
SynergyHost* synergy_applet_host_find(GList* hosts, const gchar* name, const gchar* avahi_name, const gchar* address, const uint16_t port);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
